export const FORWARD = 'w';
export const BACKWARD = 's';
export const LEFT = 'a';
export const RIGHT = 'd';
export const SPACE = ' ';
export const NEXT = '>';
export const PREVIOUS = '<';
export const X_BUTTON = 'x';
export const DIRECTIONS = [FORWARD, BACKWARD, LEFT, RIGHT];